// Dummy product list
export const getProducts = () => {
  return [
    { id: 1, name: "Laptop", price: 1200 },
    { id: 2, name: "Headphones", price: 150 },
    { id: 3, name: "Keyboard", price: 100 },
    { id: 4, name: "Mouse", price: 40 },
    { id: 5, name: "Monitor 24-inch", price: 200 },
    { id: 6, name: "Monitor 32-inch", price: 350 },
    { id: 7, name: "Smartphone", price: 900 },
    { id: 8, name: "Tablet", price: 500 },
    { id: 9, name: "Smartwatch", price: 250 },
    { id: 10, name: "Wireless Earbuds", price: 120 },
    { id: 11, name: "Bluetooth Speaker", price: 180 },
    { id: 12, name: "External Hard Drive 1TB", price: 80 },
    { id: 13, name: "External Hard Drive 2TB", price: 120 },
    { id: 14, name: "Solid State Drive 512GB", price: 90 },
    { id: 15, name: "Solid State Drive 1TB", price: 150 },
    { id: 16, name: "Gaming Laptop", price: 1600 },
    { id: 17, name: "Desktop PC", price: 1000 },
    { id: 18, name: "Mechanical Keyboard", price: 130 },
    { id: 19, name: "Gaming Mouse", price: 70 },
    { id: 20, name: "Curved Monitor 27-inch", price: 300 },
    { id: 21, name: "Smart TV 43-inch", price: 400 },
    { id: 22, name: "Smart TV 55-inch", price: 600 },
    { id: 23, name: "Smart TV 65-inch", price: 900 },
    { id: 24, name: "VR Headset", price: 500 },
    { id: 25, name: "Drone with Camera", price: 800 },
    { id: 26, name: "Action Camera", price: 250 },
    { id: 27, name: "DSLR Camera", price: 1200 },
    { id: 28, name: "Mirrorless Camera", price: 1400 },
    { id: 29, name: "Tripod Stand", price: 80 },
    { id: 30, name: "Smart Home Hub", price: 200 },
    { id: 31, name: "Smart Light Bulb", price: 40 },
    { id: 32, name: "Wi-Fi Router", price: 120 },
    { id: 33, name: "Mesh Wi-Fi System", price: 300 },
    { id: 34, name: "Portable Projector", price: 350 },
    { id: 35, name: "4K Projector", price: 1200 },
    { id: 36, name: "Streaming Stick", price: 60 },
    { id: 37, name: "Gaming Console", price: 500 },
    { id: 38, name: "Controller", price: 70 },
    { id: 39, name: "Gaming Chair", price: 250 },
    { id: 40, name: "Graphics Card", price: 700 },
    { id: 41, name: "Processor", price: 400 },
    { id: 42, name: "Motherboard", price: 250 },
    { id: 43, name: "RAM 16GB", price: 90 },
    { id: 44, name: "RAM 32GB", price: 160 },
    { id: 45, name: "Power Supply Unit", price: 110 },
    { id: 46, name: "PC Case", price: 150 },
    { id: 47, name: "Cooling Fan", price: 40 },
    { id: 48, name: "Liquid Cooler", price: 180 },
    { id: 49, name: "Webcam", price: 90 },
    { id: 50, name: "Microphone", price: 150 },
    { id: 51, name: "Wireless Charger", price: 50 },
    { id: 52, name: "Charging Cable", price: 20 },
    { id: 53, name: "Power Bank 10000mAh", price: 60 },
    { id: 54, name: "Power Bank 20000mAh", price: 100 },
    { id: 55, name: "Portable SSD 1TB", price: 180 },
    { id: 56, name: "Portable SSD 2TB", price: 300 },
    { id: 57, name: "Network Switch", price: 120 },
    { id: 58, name: "Ethernet Cable", price: 15 },
    { id: 59, name: "Printer", price: 200 },
    { id: 60, name: "3D Printer", price: 800 },
    { id: 61, name: "Scanner", price: 180 },
    { id: 62, name: "Smart Thermostat", price: 250 },
    { id: 63, name: "Smart Door Lock", price: 220 },
    { id: 64, name: "Smart Security Camera", price: 300 },
    { id: 65, name: "Video Doorbell", price: 180 },
    { id: 66, name: "Soundbar", price: 350 },
    { id: 67, name: "Home Theater System", price: 1000 },
    { id: 68, name: "Subwoofer", price: 200 },
    { id: 69, name: "Smart Glasses", price: 600 },
    { id: 70, name: "E-Reader", price: 150 },
    { id: 71, name: "Bluetooth Tracker", price: 40 },
    { id: 72, name: "Fitness Tracker", price: 120 },
    { id: 73, name: "Smart Scale", price: 90 },
    { id: 74, name: "Smart Mirror", price: 800 },
    { id: 75, name: "Electric Toothbrush", price: 70 },
    { id: 76, name: "Hair Dryer", price: 90 },
    { id: 77, name: "Air Purifier", price: 300 },
    { id: 78, name: "Robot Vacuum", price: 500 },
    { id: 79, name: "Coffee Machine", price: 250 },
    { id: 80, name: "Electric Kettle", price: 60 },
    { id: 81, name: "Blender", price: 100 },
    { id: 82, name: "Microwave Oven", price: 200 },
    { id: 83, name: "Induction Cooktop", price: 150 },
    { id: 84, name: "Refrigerator", price: 1200 },
    { id: 85, name: "Washing Machine", price: 900 },
    { id: 86, name: "Dryer", price: 800 },
    { id: 87, name: "Dishwasher", price: 700 },
    { id: 88, name: "Smart Oven", price: 1000 },
    { id: 89, name: "Portable AC", price: 500 },
    { id: 90, name: "Heater", price: 200 },
    { id: 91, name: "Ceiling Fan", price: 150 },
    { id: 92, name: "Smart Fan", price: 250 },
    { id: 93, name: "Smart Plug", price: 40 },
    { id: 94, name: "Extension Cord", price: 25 },
    { id: 95, name: "Projector Screen", price: 120 },
    { id: 96, name: "Graphics Tablet", price: 300 },
    { id: 97, name: "Drawing Monitor", price: 600 },
    { id: 98, name: "Photo Printer", price: 350 },
    { id: 99, name: "Label Maker", price: 90 },
    { id: 100, name: "Barcode Scanner", price: 150 },
  ];
};
